# Generated by Django 4.0.5 on 2023-01-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('actual_price', models.PositiveIntegerField(default=0)),
                ('sales_price', models.PositiveIntegerField(default=0)),
                ('desc', models.CharField(max_length=400)),
                ('contact', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
